### ISSUE TITLE
Add RFC 2616 Section 9 - Method Definitions

### ISSUE THREAD

**Issue by keriati** [apisyouwonthate/standards.rest#12]
I would suggest to add https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html, however I didn't figure out yet how to create the PR for it.

It describes the behaviours of http methods very well. I think this concepts would fill a gap in knowledge when people try to implement APIs.

**Comment by matthewtrask** [comment]
@keriati to make a pr, edit this [file](https://github.com/apisyouwonthate/standards.rest/blob/master/_data/standards.yml) with the relevant data.

**Comment by philsturgeon** [comment]
RFC 2616 is dead: https://www.mnot.net/blog/2014/06/07/rfc2616_is_dead.html

I added the 7230-7235 family instead.
