### ISSUE TITLE
add deprecation header

### ISSUE THREAD

**Issue by dret** [apisyouwonthate/standards.rest#14]
since the `Sunset` header is in there, maybe it makes sense to add `Deprecation` as well? http://webconcepts.info/specs/IETF/I-D/dalal-deprecation-header

**Comment by philsturgeon** [comment]
Thanks. All work is blocked because of the silly way I was using pointers. Trying to switch to jsut paths or array stuff. #15

**Comment by dret** [comment]
On 2019-03-26 11:37, Phil Sturgeon wrote:
> Thanks. All work is blocked because of the silly way I was using 
> pointers. Trying to switch to jsut paths or array stuff. #15 
> <https://github.com/apisyouwonthate/standards.rest/pull/15>

there's no hurry, i am just trying to make sure things propagate if 
that's possible. /cc @sdatspun2

**Comment by philsturgeon** [comment]
Figured! Cheers. Yeah I've had my eye on this since I saw you tweeting about it.

**Comment by philsturgeon** [comment]
Finally got around to fix things for this site, things won't get blocked up again.
