### ISSUE TITLE
Sunset is a real RFC

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/standards.rest#21]
@dret do you know why http://webconcepts.info/specs.json does not have https://tools.ietf.org/html/rfc8594 ? It's still showing http://tools.ietf.org/html/draft-wilde-sunset-header  and I'd like to show it off as a finished RFC.

**Comment by dret** [comment]
no reason other than me being forgetful. thanks for the reminder. fixed in https://github.com/dret/webconcepts/commit/3e0c790eb61f7ee473c1b2167497c993f3238c2c
